development:
  adapter: postgresql
  encoding: unicode
  database: roger
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: roger
  pool: 5
  username: myapp
  password: password1