# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e810ba879bafeaa6c10a6fbaa4cd003e0372df1aa40330f33f4b40072adede54ed6dc365d5a796d13941ef93ced7fe8a4b5868761a0172195925f02ba16991b1

test:
  secret_key_base: a3c9eb0e5abf5b5a2cd6168bf02d9160e09781284dcc363eb9dd5fbc343b3c430af424859ad4aa884165d1811528b41b2c4d2eb71e7678379a6c29f024ee2fd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
